app/urls.py
from django.urls import path
from . import views


#added namespace
app_name = 'book'
urlpatterns = [
    path("", views.BookListView.as_view(), name="list"),
    path("books/<int:pk>/", views.BookDetailView.as_view(), name="book_detail"),
]

badproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("app.urls")),
]

app/models.py
from django.db import models

class Author(models.Model):
    name = models.CharField(max_length=100)
    age = models.IntegerField()

    #added return of instances name
    def __str__(self):
        return self.name

class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    published_date = models.DateField(null=True, blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)

    def __str__(self):
        return self.title

app/views.py
from django.shortcuts import render, get_object_or_404
from .models import Book
from django.views.generic import ListView,DetailView

#Changed to generic views to simplify the code
class BookListView(ListView):
    model = Book
    template_name = "app/book_list.html"
    context_object_name = "books"

class BookDetailView(DetailView):
    model = Book
    template_name = "app/book_detail.html"
    context_object_name = "book"

app/templates/app/book_detail.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ book.title }}</h1>
    <p>{{ book.author }}</p>
    <p>{{ book.published_date }}</p>

    <a href="{% url 'book:list' %}">Back to list</a>
{% endblock %}

app/templates/app/book_list.html
{% extends "base.html" %}

{% block content %}
    <h1>Books List</h1>
    <ul>
        {% for book in books %}
            <li><a href="{% url 'book:book_detail' book.id %}">{{ book.title }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Blog</title>
</head>
<body>

{% block content %}

{% endblock %}

</body>
</html>